name: FulldevCoins
version: 1.0
description: Plugin para dropar moedas ao matar mobs
author: Konpeki Studios
main: org.konpeki_estudios.FulldevCoinsPlugin
api-version: 1.13

permissions:
  fulldevcoins.admin:
    description: Permissão para usar comandos administrativos
    default: op

commands:
  coins:
    description: Comando principal de coins
    usage: /coins [help|info|loja|reload]
    aliases: [coin, moedas]

  fulldevcoins:
    description: Comando alternativo de coins
    usage: /fulldevcoins [help|info|loja|reload]
    aliases: [fd-coins]
